### ISSUE TITLE
yo node-bahmutov:release

### ISSUE THREAD

**Issue by jimthedev** [bahmutov/generator-node-bahmutov#40]
Could npm be missing something? `yo node-bahmutov:release` doesn't seem to work on 1.29.0 and it doesn't show up in `yo --help` as a subgenerator. The docker command does show up.

**Comment by bahmutov** [comment]
Hmm, have you done `npm update -g generator-node-bahmutov` to get latest version? I just installed it and it finds it
```
$ yo node-bahmutov:app --help
Usage:
  yo node-bahmutov:app [options] 

Options:
  -h,   --help          # Print the generator's options and usage
        --skip-cache    # Do not remember prompt answers             Default: false
        --skip-install  # Do not automatically install dependencies  Default: false
```

**Comment by jimthedev** [comment]
Yes, what version are you on?

-- 
Jim ForCy

**Comment by bahmutov** [comment]
Hmm, wait, the `:app` is wrong thing, and `:release` does not work. Let me check what went wrong

**Comment by bahmutov** [comment]
`1.29.1` should fix this, I hope

**Comment by jimthedev** [comment]
I'll give it a try when back at desktop. Cheers.

-- 
Jim ForCy

**Comment by jimthedev** [comment]
Worked with 1.30.0. Thanks!

**Comment by bahmutov** [comment]
you should also be able to do `yo node-bahmutov:release --help` and other generators.
